name: ci
on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - name: set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle


      - name: Build with Gradle
        run: ./gradlew assembleCi --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: ci_build
          path: app/build/outputs/apk/debug/*.apk